name: Java CI

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests
        env:
          Email: ${{ secrets.Email }}
          Password: ${{ secrets.Password }}
        run: mvn clean test -Dheadless=true

      - name: Install Allure
        run: |
          npm install -g allure-commandline 
          wget https://github.com/allure-framework/allure2/releases/download/2.37.0/allure-2.37.0.tgz
          tar -zxvf allure-2.37.0.tgz
          sudo mv allure-2.37.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate --clean -o allure-report target/allure-results

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./allure-report
         publish_branch: gh-pages
         destination_dir: report-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Allure-Report
          path: allure-report

      - name: Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 Automation Execution Completed\nRepository: ${{ github.repository }}\nStatus: ${{ job.status }}\nReport: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/report-${{ github.run_id }}-${{ github.run_attempt }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
